### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by jbnl** [blur-network/blur#1]
Hi, the source doesn't compile with Boost 1.58 as it's stated in the readme. It asks for boost 1.62 or higher - OR 1.58 with a line pointing cmake to openssl 1.0. 

I've tried building with boost 1.58 pointing to OpenSSL 1.0 but it doesnt compile.
Also tried building with boost 1.67, no luck either. 

How do we build this?

**Comment by jbnl** [comment]
The problem had to do with openssl 1.1 being installed. Had to manually install openssl 1.0.2g and libssl-dev 1.0.2 via dpkg.

**Comment by nwiener** [comment]
Hi. now the Blur Network Block Explorer show that the height is 3901, i was solo mining for a few days two weeks ago and remember the block height was high than 3901 at that time. Is the block chain roll back？thank you

**Comment by blur-network** [comment]
Compiling errors have been fixed for Windows.  Closing this -- bugfix
