### ISSUE TITLE
chain reset?

### ISSUE THREAD

**Issue by Andy16k** [blur-network/blur#4]
hi
was mining on windows, but latest release is linux only, restored wallet from seed but balance is now 0
has the chain been reset?
block height showing as 2107?

**Comment by Andy16k** [comment]
it didnt say testnet anywhere, noob error i guess
bugger

**Comment by blur-network** [comment]
Please be advised that the old chain is NOT compatible with the new network.  Those Windows binaries are from the previous chain are invalid and your mined coins WILL BE LOST once binaries are compiled for Windows on the new chain.  Please see announcements on Discord at: https://discord.gg/VFP2VES
