### ISSUE TITLE
v0.1.9 windows issue : Synchronization fail 

### ISSUE THREAD

**Issue by vimichan** [blur-network/blur#44]
I start blurd.exe of v0.1.9 , it can't  finish synchronization  and continuely print like this:
 "SYNCHRONIZATION started
2019-02-25 01:45:56.210 [P2P9]  INFO    global  src/cryptonote_protocol/cryptono
te_protocol_handler.inl:308     [144.217.122.134:13894 OUT] Sync data returned a
 new top block candidate: 342000 -> 343762 [Your node is 1762 blocks (1 days) be
hind] " .......

please tell me how to fix it .

**Comment by vimichan** [comment]
sync successfully after an hour.

**Comment by CryptoGuy2018** [comment]
Right now this is anything than a blockchain.
You can't sync from 0 but **MUST** use a bootstrap file.
The only peers that can be used are the seed nodes.
A decentralized approach works in a different way.

**Comment by vimichan** [comment]
> Right now this is anything than a blockchain.
> You can't sync from 0 but **MUST** use a bootstrap file.
> The only peers that can be used are the seed nodes.
> A decentralized approach works in a different way.

and how to use a bootstrap file in windows? 
I found a method in md file that using command "blurd.exe --add-priority-node 66.70.189.131:13894 --add-priority-node 66.70.189.183:13894 --seed-node 66.70.188.178:13894" ,but it doesn't work as well.

**Comment by who-biz** [comment]
We're having issues with the latest fork.  Working out a solution. This issue is known. Thanks for filing a report, though.

**Comment by who-biz** [comment]
Seems to be a good amount of network interference as well.  Unfortunately, attacks are nothing new, here.

**Comment by who-biz** [comment]
resolved by 0e3d0c0704eaac1915c84d8b308d2ab549b271db
