### ISSUE TITLE
Thread stack size seems too large.

### ISSUE THREAD

**Issue by who-biz** [blur-network/blur#58]
In `src/cryptonote_config.h` the macro for `THREAD_STACK_SIZE` is defaulted to `5*1024*1024` or `0x500000`...  This should probably be `0x80000` instead. 

This may be the cause behind the the strange behavior w.r.t. to hashrate declining when we use more cores in larger processors.  We should not be allocating 5.24 MB per thread

I'm sure boost::thread provides a way to allocate thread stack size in a way that is at least somewhat portable.

**Comment by who-biz** [comment]
@leto Since I'm not very familiar with threads, if you could just give your approval that this seems correct, i'll go ahead and make the changes.  Alternatively, PR it yourself if you'd like to earn yourself a full-fledged contributor badge.

Consideration:  Our algorithm uses a 1 MB scratchpad.  Knowing that information, I'm unsure if 0x80000 or 0x40000 would be better here. Most likely the latter?

**Comment by who-biz** [comment]
This has relevance to mining in code located here: https://github.com/blur-network/blur/blob/master/src/cryptonote_basic/miner.cpp#L352

**Comment by leto** [comment]
@who-biz this seems reasonable to me :+1:

**Comment by who-biz** [comment]
Should be fixed in https://github.com/blur-network/blur/commit/f9d535baa5453d6e5a67a46b6f1f0a21f8548771.
