### ISSUE TITLE
Transaction split fee too low problem

### ISSUE THREAD

**Issue by invthr** [blur-network/blur#6]
Splitting transaction is not successful (0.1.7).

cli-wallet output:
Sending 5000.000000000000.  Your transaction needs to be split into 2 transactions.  This will result in a transaction fee being applied to each transaction, for a total fee of 0.058338900000
Is this okay?  (Y/Yes/N/No): y
Transaction successfully submitted, transaction <...db9e...920cf3...>
You can check its status by using the show_transfers command.
Error: transaction <...9e2b9...6d...89e2...cdb0...> was rejected by daemon with status: Failed
Error: Reason: fee too low

Description:
At the start there is information that tx need to be split and higher fee will be needed but finally I got around 2000 transferred with information that fee is too low (I assume for the rest amount), so maybe there is problem in code adding that additional fee.
I can see that further transfers are ending with same error but with only 1500 transferred from higher amount being submitted (around 4 of them in total).

1. first time i have sent 1000 w/o problems
2. second transfer for 9000 I got message about higher fee and I agreed to it but only 2000 were sent.
3. further 3 transfers, each time i tried to send 5000 where ending up with the same message (higher fee) but finally transfer was made only for 1500 for each of them (i accepted of course higher fee)
4. last transfer I made for 2350 was done w/o problem

Biz suggested on Discord it may be problem with not having enough BLUR to cover fees, but this is not the case. There is more than enough to cover them.

**Comment by who-biz** [comment]
Apparently still an active issue.  

Fee estimate may be the problem... or the calculation itself.  Looking into both

**Comment by who-biz** [comment]
This should be resolved in d1c7592ba4fdbdb2a4f7690ffb1d6b02eb3a0d19.
