### ISSUE TITLE
Incorrect block hash appears periodically during sync

### ISSUE THREAD

**Issue by who-biz** [blur-network/blur#63]
Errors like this one pop up periodically while syncing if full verification is enabled

`src/cryptonote_protocol/cryptonote_protocol_handler.inl:1031	[xxx.xxx.xx.xxx:52541 OUT] Got block <c45c2622079c1abf1400000000000000697e28464e7f0000140a000000000000> with unknown parent <fd365d62f979f8651708a6eb7e543730c32ff261684e3a337ffce8dd6c633be7> which was not requested - querying block hashes`

The parent block exists... but obviously the block with cleared bits does not. The temporary stall in verification resolves itself, if the daemon is just left to its own devices.

Not sure if this is happening due to a lack of proper locking during sync, or what.  The fact that it resolves itself seems to imply that verification is either being disabled temporarily to move through the failure, or that the block is being popped and sync is beginning again from the rewind point.

**Comment by leto** [comment]
I am seeing this on Ubuntu 16.04 as well, just figured I should mention

**Comment by who-biz** [comment]
Maybe a bit presumptuous, but this appears to be the area of code that is likely causing the issue: https://github.com/blur-network/blur/blob/master/src/cryptonote_protocol/cryptonote_protocol_handler.inl#L965-L1186 Noting here to come back to later, when I have proper time.

**Comment by leto** [comment]
Just giving another example here in case it's useful:

```

2019-07-29 03:13:12.419 [P2P6]  ERROR   verify  src/cryptonote_core/blockchain.cpp:3249 Block with id: <eb2ae0123ec8349a534d56e44d71e20dc6d4dd64e4b66d1ba38eaf14f24b456e>
does not have enough proof of work: <1c94bdc1942cfd934f58a717e555bf4ca34ab029d94effddf71fd7ff5490c86b>
unexpected difficulty: 12537449
```
which happens on the latest master commit 9f8a0a496859

**Comment by who-biz** [comment]
@leto you're saying that commit directly affected a change in block verification? Or something else?

These are separate bugs, I think.

**Comment by leto** [comment]
@who-biz sorry, I thought those were the same error message. Please disregard

**Comment by who-biz** [comment]
@leto No, they are indeed the same error message.  However, based on the structure of the invalid PoW hash, there appears a different catalyst behind them.  Are you able to discern if that commit precisely caused the behavior you're seeing?

**Comment by who-biz** [comment]
Either way, I think opening a separate issue report for the bug you're seeing is likely the best course of action.  It appears that the hash with zeroed bits in my original issue report is being caused by over-scanning of the data stream in the database, or something like that.  Possibly the txn being committed on an incorrect bit.

**Comment by who-biz** [comment]
@leto The padded hash that I was encountering is fixed in https://github.com/blur-network/blur/commit/5f5f88614e5a25605861235421d36fe61c880cdd.  However, I am now seeing the incorrect hash appearing as well, with an error that reads: `construct null not valid` after changing the code that writes the block hash to `stdout` to use `ostringstream`.  

So, you were correct in thinking these arise from the same underlying issue -- which seems to be translation of the block hash from binary to human-readable text... The https://github.com/blur-network/blur/commit/5f5f88614e5a25605861235421d36fe61c880cdd changes here fix the looping that was occurring, thereby speeding up sync... but doesn't fix the underlying issue, yet.  Any chance you have some insight as to a certain behavior or operation that triggers this?  

I'll continue debugging.

**Comment by who-biz** [comment]
FWIW this https://github.com/blur-network/blur/commit/2072f15df5583cba7a2c6f3b976d9f74d47aad59#diff-fca43d50a482c1d6cfb80eee7fcf688dL172 removed code from upstream, which appears to have occurred here: https://github.com/monero-project/monero/commit/c3b3260ae5b5acde445fa88a6f0909f582903754

**Comment by who-biz** [comment]
Should be fixed in: https://github.com/blur-network/blur/commit/599595d34a399dd29c0d2028f7d6604f33e70b98 

Testing now.

**Comment by leto** [comment]
@who-biz I haven't tried to use the latest code on any rigs lately, but I will be doing some rig maintenance and will let you know what I find

**Comment by who-biz** [comment]
For purposes of fully documenting the error messages: 

```
[P2P6]  INFO    blockchain      src/cryptonote_core/blockchain.cpp:3461 +++++ BLOCK SUCCESSFULLY ADDED
id:     <263faa92511dc9ff404dd50a10818050865d7d2dd29ae9081dd0685f1b22f83f>
PoW:    <c1aa6e627512f661b862712fe27a3a54a5e6cdfb34dc27834e947c1026010000>
HEIGHT 307603, difficulty:      4021419
block reward: 6.303681354997(6.303681354997 + 0.000000000000), coinbase_blob_size: 85, cumulative size: 85, 7(0/7)ms
[P2P6]  ERROR   verify  src/cryptonote_core/blockchain.cpp:3247 Block with id: <393dab3e65025386bcf8331e57b96bf6306908ae47b1ddef4ac99af747d18eea>
does not have enough proof of work: <4b01ce4976e77fd1d749ae33b660baacf99621e8983ccd320a9a65ba99c85add>
unexpected difficulty: 4091548
[P2P6]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1107    [178.44.74.113:52541 OUT] Block verification failed, dropping connection
[P2P6]  INFO    net.p2p src/p2p/net_node.inl:1617       [yyy.yy.yy.yyy:52541 yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy OUT] CLOSE CONNECTION
[P2P7]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:841     [81.93.104.15:52541 OUT] Received NOTIFY_RESPONSE_GET_OBJECTS (20 blocks, 0 txes)
[P2P7]  ERROR   net     contrib/epee/include/net/abstract_tcp_server2.inl:352   Exception at [connection<t_protocol_handler>::handle_read], what=basic_string::_M_construct null not valid
[P2P7]  INFO    net.p2p src/p2p/net_node.inl:1617       [xx.xx.xxx.xx:52541 xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx OUT] CLOSE CONNECTION
[P2P4]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:841     [66.70.189.131:52541 OUT] Received NOTIFY_RESPONSE_GET_OBJECTS (20 blocks, 0 txes)
[P2P4]  ERROR   net     contrib/epee/include/net/abstract_tcp_server2.inl:352   Exception at [connection<t_protocol_handler>::handle_read], what=basic_string::_M_construct null not valid
```

`x`s denote one node, `y`s another.  Other IP was left in, since it is a seed node address, anyway.

**Comment by who-biz** [comment]
For purposes of fully documenting the error messages: 

```
[P2P6]  INFO    blockchain      src/cryptonote_core/blockchain.cpp:3461 +++++ BLOCK SUCCESSFULLY ADDED
id:     <263faa92511dc9ff404dd50a10818050865d7d2dd29ae9081dd0685f1b22f83f>
PoW:    <c1aa6e627512f661b862712fe27a3a54a5e6cdfb34dc27834e947c1026010000>
HEIGHT 307603, difficulty:      4021419
block reward: 6.303681354997(6.303681354997 + 0.000000000000), coinbase_blob_size: 85, cumulative size: 85, 7(0/7)ms
[P2P6]  ERROR   verify  src/cryptonote_core/blockchain.cpp:3247 Block with id: <393dab3e65025386bcf8331e57b96bf6306908ae47b1ddef4ac99af747d18eea>
does not have enough proof of work: <4b01ce4976e77fd1d749ae33b660baacf99621e8983ccd320a9a65ba99c85add>
unexpected difficulty: 4091548
[P2P6]  INFO    net.cn  src/cryptonote_protocol/cryptonote_protocol_handler.inl:1107    [yyy.yy.yy.yyy:52541 OUT] Block verification failed, dropping connection
[P2P6]  INFO    net.p2p src/p2p/net_node.inl:1617       [yyy.yy.yy.yyy:52541 yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy OUT] CLOSE CONNECTION
[P2P7]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:841     [xx.xx.xxx.xx:52541 OUT] Received NOTIFY_RESPONSE_GET_OBJECTS (20 blocks, 0 txes)
[P2P7]  ERROR   net     contrib/epee/include/net/abstract_tcp_server2.inl:352   Exception at [connection<t_protocol_handler>::handle_read], what=basic_string::_M_construct null not valid
[P2P7]  INFO    net.p2p src/p2p/net_node.inl:1617       [xx.xx.xxx.xx:52541 xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx OUT] CLOSE CONNECTION
[P2P4]  INFO    net.p2p.msg     src/cryptonote_protocol/cryptonote_protocol_handler.inl:841     [66.70.189.131:52541 OUT] Received NOTIFY_RESPONSE_GET_OBJECTS (20 blocks, 0 txes)
[P2P4]  ERROR   net     contrib/epee/include/net/abstract_tcp_server2.inl:352   Exception at [connection<t_protocol_handler>::handle_read], what=basic_string::_M_construct null not valid
```

`x`s denote one node, `y`s another.  Other IP was left in, since it is a seed node address, anyway.

**Comment by leto** [comment]
@who-biz I am relatively sure that figuring out *exactly* why this happens will clear things up:

```
what=basic_string::_M_construct null not valid
```

I have seen that _M_construct null error before in Bitcoin/Zcash C++ codebase, and usually means some kind of bad data marshalling, such as an empty string attempting to be used as an object

**Comment by who-biz** [comment]
>I have seen that _M_construct null error before in Bitcoin/Zcash C++ codebase, and usually means some kind of bad data marshalling, such as an empty string attempting to be used as an object

This makes sense, because this portion of code has comments stating that the last block transmitted by a peer may be empty due to `x` circumstances. 

The part that is concerning me, is that the node syncing drops the connection on this single invalid block. So, a peer sending invalid blocks seems to cause the block streams from other peers to be considered invalid as well, and all affected connections appear to be dropped.  Sync resumes when a new connection is made, and a new block queue is populated.

**Comment by who-biz** [comment]
Disregard all of the commits above. They've been reverted as they did not solve the issue.

**Comment by leto** [comment]
@who-biz looks like you are getting closer to the entire fix.

If some nodes are calculating a hash differently than other nodes, that leads me to think that some OS-specific or compiler-specific issue is causing the calculation to be different, leading to a consensus change and the nodes forking.

Sometimes this is caused by data types meaning different things or having different sizes or bit alignments, such as `unsigned int` being 32bit or 64bit on different systems.

Do we have any data about this problem occurring only on certain OS's or perhaps only with release binaries vs compiled from source?

**Comment by who-biz** [comment]
@dukeleto

Something that I found out recently: all types suffixed with `_t` are reserved as macros on POSIX systems. Maybe related?

**Comment by leto** [comment]
@who-biz these kinds of bugs happen in Bitcoin/Zcash world in the internals of GMP, which have bugs on Windows. Most coins have their own patches for GMP to fix it

**Comment by who-biz** [comment]
> @who-biz these kinds of bugs happen in Bitcoin/Zcash world in the internals of GMP, which have bugs on Windows. Most coins have their own patches for GMP to fix it. They have to do with memory-alignment assumptions which are sometimes false.

I'll look into this as soon as I can. It sounds a bit more involved, but it may be somewhat easy to port BTC's changes, similar to what was done with the `depends` build system.

**Comment by leto** [comment]
@who-biz yes, if you look at the source code of KMD, there are various places where GMP patches are applied to fix bugs in Windows and I think also mac. All Zcash forks have these patches to make stuff work correctly across platforms, not sure any of it has ever gotten upstream to Zcash itself nor GMP.

**Comment by who-biz** [comment]
https://github.com/blur-network/blur/commit/0f148c65f3d5e41158f5484c9dd1ccc3f9358faa appears to have resolved this.  Just removed the problematic area of code, since all it was doing was a check against a block queue, which really isn't being employed properly anyway.

For whatever reasons, Monero developers appear to have intentionally crafted this into a synchronous process, which means a queue is not really necessary at all.  As a result, users are crippled into relying on ordered blocks in the queue. So I really can't see what the point of this block of code is anyway, if not simply to cause the issues we are encountering.

Will re-open if this solution doesn't suffice.
