### ISSUE TITLE
Documentation explaining Blur interoperability

### ISSUE THREAD

**Issue by Mikerah** [blur-network/blur#72]
I'm a researcher in the blockchain space and I recently stumbled upon the Blur Network. One of the claims made is that it aims to be interoperable with BTC, XMR and ZEC. However, there is no documentation explaining the mechanisms used to achieve this. Is there any documentation I can read to learn more about this?

**Comment by who-biz** [comment]
@Mikerah you can find the code being written toward that goal here: https://github.com/blur-network/dpow-blur 

Interoperability is not yet possible. But, that repo is capable of handling BTC-specific types and structures. 

If you have further questions, please open an issue on that repo instead.

**Comment by who-biz** [comment]
Closing due to being opened on the incorrect repo.
