### ISSUE TITLE
Still lying about the algorithm on the website

### ISSUE THREAD

**Issue by fart-master** [blur-network/blur#79]
Why not just tell the truth. GPUs work, pools work. the algorithm does not need to be updated every 5 seconds and the algorithm requires no access to historical block data.

**Comment by lazaridiscom** [comment]
Hey, even high-profile projects are lying, usually without reason.

This one is a very low traffic project.

If you think they lie, they're possibly just lazy to update the site / code.

**Comment by fart-master** [comment]
They did update the website. that's the point. I raised the same issue weeks ago. they updated the website and kept misleading information in there.

**Comment by lazaridiscom** [comment]
Seeing issue #71 i can tell you that this is not how a malicious actor operates, at least they do not block you.


me not sure why I watch this repo, but i think(!) i started watching it because of the "CPU ONLY" argument (which the graphic on the website very very clearly communicates: CPU ONLY).

But if you're right, then it's possibly the easiest to just produce a tiny video or so.

But what is this about for you? what would be your benefit of proofing that they "don't tell the truth"?

**Comment by lazaridiscom** [comment]
Addidtionally, are you aware that this is a solo-contributor project:

https://github.com/blur-network/blur/graphs/contributors

**Comment by fart-master** [comment]
Another sheep i see. Cause sure. Why would we want people that claim to be honest and transparent to actually operate honestly?

**Comment by fart-master** [comment]
And it did get locked. he just unlocked that issue after it was buried in the closed issues

**Comment by lazaridiscom** [comment]
Of course I'm a dumb sheep, otherwise I would not talk to a fartmaster at dawn.

If you are in the mood for truth, attack larger projects like tezos or cosmos.

I do not understand why you place so much value in this project.

**Comment by fart-master** [comment]
You don't seem to understand. I place no value in blur. I do place value in holding biz to account. He is a liar that tries to make a name for himself attacking other projects. All i am doing is giving him back what he so happily hands out

**Comment by who-biz** [comment]
Closing due to pointless banter.

**Comment by who-biz** [comment]
I’d like to remind everyone that the issue tracker is for real issues in code. Not slander du jour

**Comment by who-biz** [comment]
I do agree, though, that Cosmos is doing some very cool things.
