### ISSUE TITLE
You are free to do that elsewhere. 

### ISSUE THREAD

**Issue by lazaridiscom** [blur-network/blur#81]
You are free to do that elsewhere. This medium (issue tracker) is for issues in code. There are plenty of social places for chit-chat. 

Things posted here are for A.) My reference B.) The reference of potential contributors and C.) The reference of our users so that they may be informed about potential issues in software. 

Commentary and opinion have their place in their proper areas, too.

_Originally posted by @who-biz in https://github.com/blur-network/blur/issues/80#issuecomment-589911057_

You need to grasp that "writing a comment and locking" is equal with saying something and then keeping the other persons mouth forcefully closed.

Another term is "Fascism".

Reflect on this, you weirdo.

**Comment by who-biz** [comment]
No, “fascism” would be me not allowing you to continue with the ad hominem attacks.

I’m requesting civility, and to stop getting in the way of useful info for our users.

**Comment by lazaridiscom** [comment]
See, wasn't so difficult.

Criticism is always valid feedback. So, let this "fart" talk, your users can simply select to Unsubscribe the issue.

**Comment by who-biz** [comment]
Criticism is good. Pointlessly contrary viewpoints that run themselves up trees, repeatedly, are not. The latter is strictly counter-productive.

**Comment by lazaridiscom** [comment]
Well, I was interested. The only reason I followed this project was the "CPU ONLY" claim. So, even if there is much noise, I'd like to hear what he has to say.

**Comment by lazaridiscom** [comment]
but ok, giving up now.

**Comment by lazaridiscom** [comment]
hey, @who-biz , you can delete the issues I've filed

**Comment by who-biz** [comment]
Yes, our CPU-only assumption was inherited from our upstream. I’ve said many times we won’t resist hardware adaptation. Doing so makes no sense at all.

I’ve thanked fart for his development of a GPU miner, despite being developed adversarially. That kind of stuff, we welcome.

**Comment by lazaridiscom** [comment]
delete the issues.
