### ISSUE TITLE
Cannot open CLI wallet of Blur

### ISSUE THREAD

**Issue by JustFragger** [blur-network/blur#82]
Hello !
There"s an error in CLI wallet so I can"t create or open blur-cli-wallet.ex.
Here"s what it says : `terminate called after throwing an instance of 'boost::system::system_error'
  what():  boost::filesystem::path codecvt to wstring: error`
I have for this time GUI walelt , but every time i want open it , it says couldnt open wallet : invalid password , so I have to all the way recover it from seed :/

hope it will be fixed >3
Kind Regards
-Mathew S.

**Comment by who-biz** [comment]
@JustFragger 

Please see if the issue persists on the latest version, here: https://github.com/blur-network/blur/releases

**Comment by JustFragger** [comment]
> @JustFragger
> 
> Please let me know, if the issue still persists on the latest version (v0.1.9.9.4), here: https://github.com/blur-network/blur/releases

Hello @who-biz 

Problem still persists on latestest version , nothing changed same error as I wrote above.
OS: Windows 10 Home (Standard)

**Comment by who-biz** [comment]
Thanks for quick response. Will check it out today on a Windows machine. I’ll update you once I have a look at it!

For now, as a temporary workaround, I would recommend using the GUI, or downgrading to an earlier version of the wallet (v0.1.9.9.1 and earlier should work fine)

**Comment by who-biz** [comment]
Just a note that downgrading daemon isn’t necessary. Previous wallet versions should work just fine with a newer version of daemon

**Comment by who-biz** [comment]
@JustFragger any chance you could provide some logs so that we can get to the bottom of this issue?

**Comment by JustFragger** [comment]
> @JustFragger any chance you could provide some logs so that we can get to the bottom of this issue?

Yeah, here it is : (it"s full log from CMD CLI wallet window no more it says) 
```
terminate called after throwing an instance of 'boost::system::system_error'
  what():  boost::filesystem::path codecvt to wstring: error
```
I can say , that GUI wallet is working but there"s bug when I enter correct password it says invalid so i have to recover from seed again and again ....

**Comment by who-biz** [comment]
@JustFragger I was unable to reproduce this error on Windows 10 Home, when running the release that will be uploaded shortly (v0.1.9.9.5).  

Are you using a non-English language, by any chance?

Also, if you don't mind, try creating a wallet file without a password, and see if you can open that.  Trying to track down where this is coming from. In my testing, I did not set a password during wallet generation.

**Comment by who-biz** [comment]
Actually, just tested with a password as well. All seems in order. Recommend running the wallet from the latest release, once posted. Should be tagged/uploaded later this evening.

**Comment by JustFragger** [comment]
@who-biz Im using my own language not English so maybe theres problem but i dont know , lets give it try >3
Thanks for looking at it

**Comment by who-biz** [comment]
Sure thing! Let me know if you have issues still, when using English locale. I'll also begin digging to the bottom of the issue with other languages.  Only supporting English is non-ideal, of course.

Thanks again for reporting this.
