### ISSUE TITLE
Prereqs missing for Mac build on Ubuntu

### ISSUE THREAD

**Issue by trurebel** [blur-network/blur#84]
Probably very few have tried building this project lately, I copied and pasted commands to build for Mac and, so far: pip needs to be installed, ez_setup needs to be pipped and

`home/ubuntu/blur/contrib/depends/work/download/native_cctools-807d6fd1be5d2224872e381870c0a75387fe05e6/clang-llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz.temp: OK
Extracting native_cctools...
/home/ubuntu/blur/contrib/depends/sources/807d6fd1be5d2224872e381870c0a75387fe05e6.tar.gz: OK
/home/ubuntu/blur/contrib/depends/sources/clang-llvm-3.7.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz: OK
Preprocessing native_cctools...
libtoolize:   error: One of these is required:
libtoolize:                 gm4 gnum4 m4
libtoolize:   error: Please install GNU M4, or 'export M4=/path/to/gnu/m4'.
./autogen.sh: line 23: aclocal: command not found
./autogen.sh: line 24: autoconf: command not found
./autogen.sh: line 26: automake: command not found
`

Some m4 fix? And probably more

**Comment by trurebel** [comment]
got m4, automake, libcap-dev but, still:

`  Error: found a Linux system but no libcap header.  Install libcap-dev.
`

**Comment by who-biz** [comment]
It looks like you are missing `autoconf`.

You should be able to proceed if you install that package. However, if you are trying to cross-compile for Mac... you will run into more errors further in compilation. 

I’ve not been able to get the `depends` build system functioning for macOS, unfortunately. Our binaries for macOS are never cross-compiled, as  result.

**Comment by who-biz** [comment]
That said, `pip` and `ez_setup` are requirements, so I can add some notes about it

**Comment by who-biz** [comment]
A note has been added about the failing macOS cross-compilation Makefile options.

https://github.com/blur-network/blur/commit/a457426727bf1a8d4763a5b70206bca1faf52d45

**Comment by who-biz** [comment]
Please note we have started work toward fixing this issue as of commit https://github.com/blur-network/blur/commit/cf6063a9836f8513c264fc458260cd0d21921f11... will keep this report updated with progress toward a working mac cross-compilation

**Comment by who-biz** [comment]
@trurebel you'll find macOS cross compilation to be functional as of commit 4a2dab8ae2f51ad6985fb649e4a381f19bf58557.

Closing this issue
