### ISSUE TITLE
Ultraminor, but your mining cli example with blurd mixes up the = with the _space_ notation

### ISSUE THREAD

**Issue by trurebel** [blur-network/blur#85]
presumably both = and space work for blurd's command line options, but the example you give somewhat confusingly reverses what you show in the previous line

**Comment by who-biz** [comment]
@trurebel that is true on Linux, that both spaces and `=` will work for specifying command-line options. 

On Windows, however, I believe, both, the equal signs, and quotes are necessary... particularly if using a `.bat` file for launching.

If that’s not what you meant, please elaborate further and we can fix whatever discrepancies exist.

**Comment by trurebel** [comment]
If Windows needs both, best give all examples in that style.

**Comment by who-biz** [comment]
This is a good idea. Thanks. Will amend accordingly

**Comment by who-biz** [comment]
Please note that procedure on <a href="https://github.com/blur-network/blur/releases">Releases page</a> will be updated upon next release. 

@trurebel, if you would, please check that the source of this issue is properly corrected.

**Comment by who-biz** [comment]
Just a note that releases page has been updated with your recommended changes.  Thanks again for reporting.
