### ISSUE TITLE
unknown command: show_hr

### ISSUE THREAD

**Issue by piotr-sikora-v** [blur-network/blur#87]
I have latest version from github and my blur-wallet-cli don't kwno this option

same in blur-v0.1.9.9.5-linux_x86_64 from snap.

**Comment by who-biz** [comment]
`show_hr` needs to be typed into the running `blurd` interface, not `blur-wallet-cli`.

Try that, and it should work.  Let me know if it doesn't, however.

**Comment by piotr-sikora-v** [comment]
yes it wokrs, now it start loggin in to stdout/logfile.
is any option to turn off loggin this ?

**Comment by who-biz** [comment]
> is any option to turn off logging?

Yes. `hide_hr` will do that.  You can find more commands for the daemon, by typing `help` into the running `blurd` interface.

**Comment by who-biz** [comment]
Closing as resolved.
