### ISSUE TITLE
Sync gets stuck on Windows CLI

### ISSUE THREAD

**Issue by awestsecurity** [blur-network/blur#88]
I started a new node with the most recent version of the CLI and syncing became stuck many times throughout the process. Restarting `blurd` temporarily resolved the issue. The time between getting stuck was inconsistent. Anywhere from 1,000 - 60,000 blocks. No new message is displayed when sync stopped. Syncing could complete after many restarts.

My operating system is Windows 10, 64bit

**Comment by who-biz** [comment]
Thanks for opening this issue.  We cross-compile our Windows binaries using a Linux host.  It's possible that compiling with `mingw` on a Windows host might resolve this issue.

marking this as under-investigation pending some digging.

**Comment by who-biz** [comment]
This can be rectified by adding seed node network addresses with `--add-priority-node=<IP>` to `blurd` startup options
